### PR TITLE
Josh's edits

### PR DESCRIPTION
**Pull request by Caladrel65**
Small changes. I'd like this to be merged to your branch so I can then grab the changes you've made and start fresh.

### CODE REVIEW

**Comment by Caladrel65** [comment]
Making some adjustments to match your code.

**Review by Caladrel65 — COMMENTED** [review]
Changes are mainly grammar edits. The password for the local host is different so you'd need to copy yours and recommit that.

**Comment by Caladrel65** [comment]
Okay, went in and resolved conflicts. You can double check this if you'd like. I set it to keep your password when it is merged.

**Review by Brad3nD — APPROVED** [review]
Looks Good!

**Pull request merged**
